### ISSUE TITLE
Support Nested Arrays

### ISSUE THREAD

**Issue by dstebila** [captn3m0/jekyll-sqlite#6]
Is it possible to do nested arrays?  For example, would it be possible to extend the example in the README to a third level as shown below (assuming the appropriate tables were defined):

```yaml
sqlite:
  - data: suppliers
    file: "_db/northwind.db"
    query: "SELECT CompanyName, SupplierID FROM suppliers ORDER BY SupplierID"
  - data: suppliers.products
    # This is a prepared query, where SupplierID is coming from the previous query.
    file: "_db/northwind.db"
    query: "SELECT ProductName, CategoryID,UnitPrice FROM products WHERE SupplierID = :SupplierID"
  - data: suppliers.products.reviews
    file: "_db/northwind.db"
    query: "SELECT * FROM reviews WHERE ProductName = :ProductName"
```

When I try to do so, I get an error like the following:
```
.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/jekyll-sqlite-0.1.5/lib/jekyll-sqlite/generator.rb:22:in `block in get_root': no implicit conversion of String into Integer (TypeError)
```
